# Generated by Django 4.1 on 2022-09-24 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField()),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField()),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('nickname', models.CharField(max_length=256)),
                ('is_admin', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField()),
                ('image_filename', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='issuetracker.user')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuetracker.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField()),
                ('image_filename', models.CharField(blank=True, max_length=128)),
                ('text', models.CharField(max_length=512)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='issuetracker.user')),
                ('parent_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuetracker.issue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='issuetracker.user'),
        ),
    ]
