# Generated by Django 4.1 on 2023-07-09 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image_filename',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='image_filename',
        ),
    ]
